/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hotta.jun' at '17/08/02 11:22' with Gradle 2.14.1
 *
 * @author hotta.jun, @date 17/08/02 11:22
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
